# Generated by Django 4.1 on 2022-10-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0003_zapatilla_imagen_zapatilla_user_alter_avatar_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapatilla',
            name='user',
        ),
    ]
