# Generated by Django 4.1 on 2022-10-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0005_zapatilla_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatilla',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
