# Generated by Django 4.1 on 2022-10-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajeria', '0002_remove_message_receptor_message_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='emisor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id_chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
