# Generated by Django 4.1 on 2022-10-11 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppMensajeria', '0003_remove_message_emisor_remove_message_id_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='emisor_id', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('fecha', models.DateField(null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='emisor_id', to=settings.AUTH_USER_MODEL)),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMensajeria.chat')),
            ],
        ),
    ]
